import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/global.css';
import Toaster from '@/components/toaster';
import ProtectRoute from '@/utils/hooks/protectRoute';
import AuthProvider from '@/contexts/auth';
import PostProvider from '@/contexts/post';
import ThemeRegistry from '@/components/themeRegistry/ThemeRegistry';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeRegistry>
          <Toaster />
          <AuthProvider>
            <PostProvider>
              <ProtectRoute>{children}</ProtectRoute>
            </PostProvider>
          </AuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
