import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import '../styles/global.css';
import Toaster from '@/components/toaster';
import ProtectRoute from '@/utils/hooks/protectRoute';
import AuthProvider from '@/contexts/auth';
import PostProvider from '@/contexts/post';

const lexend = Lexend({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'My Blog',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={lexend.className}>
				<Toaster />
				<AuthProvider>
					<PostProvider>
						<ProtectRoute>{children}</ProtectRoute>
					</PostProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
