import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import '../styles/global.css';
import Toaster from '@/components/toaster';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'My Blog',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={lexend.className}>
				<Toaster />
				{children}
			</body>
		</html>
	);
}
